### ISSUE TITLE
[help]安装不成功

### ISSUE THREAD

**Issue by SEAHAISEA** [winsoft666/electron-vue3-boilerplate#11]
electron安装不成功，win10,它是卡在那不动了...😅

![Snipaste_2024-07-15_23-12-23](https://github.com/user-attachments/assets/01a9ef49-677b-47f0-acd6-0255eebdedf5)

**Comment by winsoft666** [comment]
网络问题导致的，可以尝试设置国内源（目前国内源也不稳定了），翻墙比较靠谱

**Comment by winsoft666** [comment]
可以使用这个方法：
https://github.com/electron/electron/issues/8466#issuecomment-571425574

**Comment by SEAHAISEA** [comment]
感谢，已解决，成功运行！😅

在yarn install之前，yarn增加一个配置

yarn config set electron_mirror https://npmmirror.com/mirrors/electron/
