### ISSUE TITLE
如何IDE调试可以补充介绍下吗

### ISSUE THREAD

**Issue by zhangqiangboss** [winsoft666/electron-vue3-boilerplate#12]
调试的配置相关

**Comment by liusongyb** [comment]
https://electron.nodejs.cn/docs/latest/tutorial/debugging-vscode

**Comment by winsoft666** [comment]
需要自定义vscode的launch.json文件，大致步骤如下：
1. 编译ts为js
2. 启动renderer进程
3. 获取renderer服务端口号，并启动electron进行调试
