### ISSUE TITLE
Error report for electron-vue3-boilerplate 1.0.1

### ISSUE THREAD

**Issue by liusongyb** [winsoft666/electron-vue3-boilerplate#13]
Error:
```Error: Failed to load image from path 'F:\electron\electron-vue3-boilerplate-main\static\tray.ico'
    at CreateAppTray (F:\electron\electron-vue3-boilerplate-main\build\main\tray.js:41:18)
    at F:\electron\electron-vue3-boilerplate-main\build\main\main.js:30:61
```
OS: Windows NT 10.0.22631

**Comment by liusongyb** [comment]
使用vscode调式报错

**Comment by liusongyb** [comment]
![er1](https://github.com/user-attachments/assets/e2249116-2812-4975-b6fd-ca78ae079b46)

**Comment by winsoft666** [comment]
哦哦，应该是图片路径问题，容我看看~~

**Comment by liusongyb** [comment]
我是新手，感谢大神的框架，终于找到怎么开头，现在就是调试问题能不能做到点击
<img width="593" alt="el2" src="https://github.com/user-attachments/assets/006d3afe-4ebb-4ab1-aa2a-0a2f55bdd430">
我现在的产品是跑到windows下，原来是打算使用flutter，但是调用USB摄像头的问题解决不了，才转入的electron。大神可以加入vscode如何调式，框架的吸引力就更强了。
