### ISSUE TITLE
Vue: Cannot find module @file-download/renderer or its corresponding type declarations 

### ISSUE THREAD

**Issue by halfhoney2018** [winsoft666/electron-vue3-boilerplate#19]
<img width="713" alt="image" src="https://github.com/user-attachments/assets/26c15685-bf18-4529-b396-7d2ea3c31bef">
  楼主 遇到这个错误是啥原因

**Comment by winsoft666** [comment]
安装Vue - Official 插件，然后：
1、在当前项目的工作空间下，用 Ctrl + Shift + P (macOS：Cmd + Shift + P) 唤起命令面板。
2、输入 built，然后选择“Extensions：Show Built-in Extensions”。
3、在插件搜索框内输入 typescript (不要删除 @builtin 前缀)。
4、点击“TypeScript and JavaScript Language Features”右下角的小齿轮，然后选择“Disable (Workspace)”。
