### ISSUE TITLE
在mac下面有很多问题

### ISSUE THREAD

**Issue by jijin51** [winsoft666/electron-vue3-boilerplate#3]
1.打包之后安装dmg文件，打开程序白屏。
2.开发环境点击程序左上角关闭按钮再点击弹窗里的确认，程序卡死，杀进程都杀不掉。
3.开发环境更新卡死，杀进程都杀不掉。
...
目前是这么多，开发环境的几个问题解决了，打包之后的问题没时间弄了...

**Comment by jijin51** [comment]
修正：3.开发环境热更新导致程序卡死，杀进程都杀不掉。

**Comment by 15886485069** [comment]
mac m1 芯片；yarn dev运行一段时间后，某次启动突然自动跳转到 nginx 页面
![nginx](https://github.com/winsoft666/electron-vue3-boilerplate/assets/66773610/152b8096-1f65-4d4a-b399-149e802f5df8)

**Comment by winsoft666** [comment]
> mac m1 芯片；yarn dev运行一段时间后，某次启动突然自动跳转到 nginx 页面 ![nginx](https://private-user-images.githubusercontent.com/66773610/332692788-152b8096-1f65-4d4a-b399-149e802f5df8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjI3NTIsIm5iZiI6MTcxNjM2MjQ1MiwicGF0aCI6Ii82Njc3MzYxMC8zMzI2OTI3ODgtMTUyYjgwOTYtMWY2NS00ZDRhLWIzOTktMTQ5ZTgwMmY1ZGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA3MjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNmIzOTIzNDQ4ODgzMjZkNDc5MzRjMThlNWE2NWM2MTI0OGExNzI3ZGYzYWNiZjY0NDIwM2Q2ZjZiYzE3ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ika4je_odp3xuxyb2z84Fx9Z2amLiX1ij1yM0haSw2s)

这个应该是你内嵌页面的问题，模板本身没有访问任何其他Nginx服务

**Comment by 15886485069** [comment]
> > mac m1 芯片；yarn dev运行一段时间后，某次启动突然自动跳转到 nginx 页面 ![nginx](https://private-user-images.githubusercontent.com/66773610/332692788-152b8096-1f65-4d4a-b399-149e802f5df8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjI3NTIsIm5iZiI6MTcxNjM2MjQ1MiwicGF0aCI6Ii82Njc3MzYxMC8zMzI2OTI3ODgtMTUyYjgwOTYtMWY2NS00ZDRhLWIzOTktMTQ5ZTgwMmY1ZGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA3MjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNmIzOTIzNDQ4ODgzMjZkNDc5MzRjMThlNWE2NWM2MTI0OGExNzI3ZGYzYWNiZjY0NDIwM2Q2ZjZiYzE3ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ika4je_odp3xuxyb2z84Fx9Z2amLiX1ij1yM0haSw2s)
> 
> 这个应该是你内嵌页面的问题，模板本身没有访问任何其他Nginx服务
>
>依旧是这个模版，没有任何改动；（这个模板很精简）

**Comment by 15886485069** [comment]
> mac m1 芯片；yarn dev运行一段时间后，某次启动突然自动跳转到 nginx 页面 ![nginx](https://private-user-images.githubusercontent.com/66773610/332692788-152b8096-1f65-4d4a-b399-149e802f5df8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjgwMDcsIm5iZiI6MTcxNjM2NzcwNywicGF0aCI6Ii82Njc3MzYxMC8zMzI2OTI3ODgtMTUyYjgwOTYtMWY2NS00ZDRhLWIzOTktMTQ5ZTgwMmY1ZGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA4NDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmYWE2MzAxNWI5Y2EwZmNhMDNjZTg4MjlhMTEzNTIyMzllNDlkMmMyMjU3OTYwN2M1YjkwMjdlMGE3NDEzMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xzcQN4vF44QLAXl-ZULMuVwoL5Yn3NXk6n45ceUfsRc)

端口号冲突，更改端口号即可

**Comment by winsoft666** [comment]
Fixed some bugs on macOS, please try again.
