### ISSUE TITLE
执行pnpm run build:win64打包时报错

### ISSUE THREAD

**Issue by gyh333** [winsoft666/electron-vue3-boilerplate#4]
![image](https://github.com/winsoft666/electron-vue3-boilerplate/assets/6347047/2697fd82-bd14-4f09-86c4-31cd0b82a719)
node版本：18.17.1
pnpm版本：8.15.4
在执行pnpm run build:win64后出现报错，请问是什么原因

**Comment by winsoft666** [comment]
使用yarn命令，
yarn run build:win64

**Comment by gyh333** [comment]
只能使用yarn命令吗

**Comment by winsoft666** [comment]
我开发和测试都用的yarn，未测试其他工具，理论上其他工具也是可以的，如果使用yarn之外的工具出现问题，还需要自行解决。

**Comment by gyh333** [comment]
好的，谢谢
