### ISSUE TITLE
报错：谷歌登录，浏览器不支持 JavaSscript 或关闭了 JavaSscript

### ISSUE THREAD

**Issue by 15886485069** [winsoft666/electron-vue3-boilerplate#9]
![iwEcAqNwbmcDAQTRA-IF0QP0BrB0IUkx7fGZVAZJ4JUtZv4BB9IREx3FCAAJomltCgAL0gABOBI png_720x720q90](https://github.com/winsoft666/electron-vue3-boilerplate/assets/66773610/fd3216e1-904d-474b-918e-c8662608cc73)
![iwEdAqNwbmcDAQTRAkkF0QFjBrDvXatmv4870QZJ4JUtZv4AB9IREx3FCAAJomltCgAL0gAAtnQ png_720x720q90](https://github.com/winsoft666/electron-vue3-boilerplate/assets/66773610/1e1a4957-3300-4a50-af46-ac4caa5a8b27)

**Comment by winsoft666** [comment]
这个问题应该不是项目的问题，也许是Electron参数设置问题，或者Electron的bug。

顺便提一句，可以尝试关闭 nodeIntegration
